include:
  - board: seeeduino_xiao_ble
    sheild: Ergocres_R rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    sheild: Ergocres_L rgbled_adapter
  - board: seeeduino_xiao_ble
    sheild: settings_reset