include:
  - board: seeeduino_xiao_ble
    sheild: Ergocresce_R rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    sheild: Ergocresce_L rgbled_adapter
  - board: seeeduino_xiao_ble
    sheild: settings_reset